---
bind_acls:
  - name: trusted
    match_list:
      - 127.0.0.1
      - 10.0.0.0/24
bind_allow_query:
  - trusted
bind_forwarders:
  - 62.210.16.6
  - 62.210.16.7
bind_listen_ipv4:
  - 127.0.0.1
  - 10.0.0.1
bind_recursion: true
bind_zone_domains:
  - name: sd-51798.dy2k.io
    networks:
      - '10.0.0'
    name_servers:
      - ns1.sd-51798.dy2k.io.
      - ns2.sd-51798.dy2k.io.
    hostmaster_email: admin
    hosts:
      - name: ns1
        ip: 10.0.0.1
      - name: ns2
        ip: 10.0.0.2
      - name: gateway1
        ip: 10.0.0.1
      - name: gateway2
        ip: 10.0.0.2
      - name: kube-cluster1
        ip: 10.0.0.10
      - name: kube-master1
        ip: 10.0.0.11
      - name: kube-master2
        ip: 10.0.0.12
      - name: kube-master3
        ip: 10.0.0.13
      - name: kube-worker1
        ip: 10.0.0.21
      - name: kube-worker2
        ip: 10.0.0.22
      - name: kube-worker3
        ip: 10.0.0.23
bind_zone_master_server_ip: 10.0.0.1
