---
- name: Allow OpenSSH in ufw
  ufw:
    rule: allow
    name: OpenSSH
  when: inventory_hostname == groups["gateways"][0]

- name: Enable UFW
  ufw:
    state: enabled
  when: inventory_hostname == groups["gateways"][0]

- name: Change forward policy
  lineinfile:
    path: /etc/default/ufw
    regexp: '^DEFAULT_FORWARD_POLICY="DROP"'
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'
    backrefs: yes
  when: inventory_hostname == groups["gateways"][0]
  notify:
    - Restart ufw

- name: Set sysctl to forward
  lineinfile:
    path: /etc/ufw/sysctl.conf
    regexp: "^#net/ipv4/ip_forward=1"
    line: "net/ipv4/ip_forward=1"
    backrefs: yes
  when: inventory_hostname == groups["gateways"][0]
  notify:
    - Restart ufw

- name: Add NAT to ufw
  blockinfile:
    path: /etc/ufw/before.rules
    block: |
      # NAT table rules
      *nat
      :POSTROUTING ACCEPT [0:0]
      # Forward traffic through out-interface - Change to match yours
      -A POSTROUTING -s {{ nat_cidr }} -o {{ nat_interface }} -j MASQUERADE
      # don't delete the 'COMMIT' line or these nat table rules won't
      # be processed
      COMMIT
    insertbefore: "^# Don't delete these required lines"
  when: inventory_hostname == groups["gateways"][0]
  notify:
    - Restart ufw

- name: Flush handlers
  meta: flush_handlers